// <auto-generated />
using System;
using EnergyInforamtionBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnergyInforamtionBot.Migrations
{
    [DbContext(typeof(EIADataContext))]
    [Migration("20230330010101_CreateEIADb")]
    partial class CreateEIADb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnergyInforamtionBot.EIASeriesItem", b =>
                {
                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Period");

                    b.ToTable("SeriesItems");
                });
#pragma warning restore 612, 618
        }
    }
}
